server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: shcm-platform
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.shcm.entity # 别名扫描包
logging:
  level:
    com.shcm: debug


