spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxx:23241/shcm_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: xxxx
  redis:
    host: xxx
    port: 6379
    password: 'xxxx'
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

IMAGE_UPLOAD_DIR: 'D:\workspace\IDEA\shcm-html_nginx-1.18.0\html\shcm-html\imgs'