server:
  port: 8081
spring:
  application:
    name: shcm-platform
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.56.92.162:3306/shcm_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 123.56.92.162
    port: 6379
    password: '123456'
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.shcm.entity # 别名扫描包
logging:
  level:
    com.shcm: debug